<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Objects\" />
    <None Remove="FileProcessing\" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Objects\" />
    <Folder Include="FileProcessing\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Telegram.Bot" Version="19.0.0" />
  </ItemGroup>
</Project>
